namespace AksonApp.Migrations
{
    using AksonApp.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<AksonApp.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            ContextKey = "AksonApp.Models.ApplicationDbContext";
        }

        protected override void Seed(AksonApp.Models.ApplicationDbContext context)
        {
            using(Models.ApplicationDbContext db = new Models.ApplicationDbContext())
            {
                string[] service = { "Brake fluid flush overdue",
                                     "Front brake pads due",
                                     "Rear brake pads due",
                                     "Micro filter due",
                                     "Statutory emmissions due",
                                     "Vehicle check service due",
                                     "Service overdue" };

                bool checkIfExits = db.ServiceTypes.Any();
                if (!checkIfExits)
                {
                    for (int i = 0; i <= service.Length - 1; i++)
                    {
                        ServiceTypes serviceTypes = new ServiceTypes()
                        {
                            Name = service[i]
                        };
                        db.ServiceTypes.Add(serviceTypes);
                        db.SaveChanges();
                    }      
                }

                string[] phoneCodes = { "+247",
                "+376",
                "+971",
                "+93",
                "+1-268",
                "+1-264",
                "+355",
                "+374",
                "+599",
                "+244",
                "+54",
                "+1-684",
                "+43",
                "+61",
                "+297",
                "+358-18",
                "+374-97",
                "+994",
                "+387",
                "+1-246",
                "+880",
                "+32",
                "+226",
                "+359",
                "+973",
                "+257",
                "+229",
                "+1-441",
                "+673",
                "+591",
                "+55",
                "+1-242",
                "+975",
                "+267",
                "+375",
                "+501",
                "+1",
                "+61",
                "+243",
                "+236",
                "+242",
                "+41",
                "+225",
                "+682",
                "+56",
                "+237",
                "+86",
                "+57",
                "+506",
                "+381",
                "+53",
                "+238",
                "+61",
                "+90-392",
                "+357",
                "+420",
                "+49",
                "+253",
                "+45",
                "+1-767",
                "+1-809",
                "+213",
                "+593",
                "+372",
                "+20",
                "+212",
                "+291",
                "+34",
                "+251",
                "+358",
                "+679",
                "+500",
                "+691",
                "+298",
                "+33",
                "+241",
                "+44",
                "+1-473",
                "+995",
                "+594",
                "+44",
                "+233",
                "+350",
                "+299",
                "+220",
                "+224",
                "+590",
                "+240",
                "+30",
                "+502",
                "+1-671",
                "+245",
                "+592",
                "+852",
                "+504",
                "+385",
                "+509",
                "+36",
                "+62",
                "+353",
                "+972",
                "+44",
                "+91",
                "+246",
                "+964",
                "+98",
                "+354",
                "+39",
                "+44",
                "+1-876",
                "+962",
                "+81",
                "+254",
                "+996",
                "+855",
                "+686",
                "+269",
                "+1-869",
                "+850",
                "+82",
                "+965",
                "+1-345",
                "+7",
                "+856",
                "+961",
                "+1-758",
                "+423",
                "+94",
                "+231",
                "+266",
                "+370",
                "+352",
                "+371",
                "+218",
                "+212",
                "+377",
                "+373-533",
                "+373",
                "+382",
                "+261",
                "+692",
                "+389",
                "+223",
                "+95",
                "+976",
                "+853",
                "+1-670",
                "+596",
                "+222",
                "+1-664",
                "+356",
                "+230",
                "+960",
                "+265",
                "+52",
                "+60",
                "+258",
                "+264",
                "+687",
                "+227",
                "+672",
                "+234",
                "+505",
                "+31",
                "+47",
                "+977",
                "+674",
                "+683",
                "+64",
                "+968",
                "+507",
                "+51",
                "+689",
                "+675",
                "+63",
                "+92",
                "+48",
                "+508",
                "+1-787", // and 1-939 ?
                "+970",
                "+351",
                "+680",
                "+595",
                "+974",
                "+262",
                "+40",
                "+381",
                "+7",
                "+250",
                "+966",
                "+677",
                "+248",
                "+249",
                "+46",
                "+65",
                "+290",
                "+386",
                "+47",
                "+421",
                "+232",
                "+378",
                "+221",
                "+252",
                "+252",
                "+597",
                "+239",
                "+503",
                "+963",
                "+268",
                "+290",
                "+1-649",
                "+235",
                "+228",
                "+66",
                "+992",
                "+690",
                "+670",
                "+993",
                "+216",
                "+676",
                "+90",
                "+1-868",
                "+688",
                "+886",
                "+255",
                "+380",
                "+256",
                "+1",
                "+598",
                "+998",
                "+379",
                "+1-784",
                "+58",
                "+1-284",
                "+1-340",
                "+84",
                "+678",
                "+681",
                "+685",
                "+967",
                "+262",
                "+27",
                "+260",
                "+263"
            };

                bool checkIfPhoneCodeExits = db.PhoneCodes.Any();
                if (!checkIfPhoneCodeExits)
                {
                    for (int i = 0; i <= phoneCodes.Length - 1; i++)
                    {
                        PhoneCodes codes = new PhoneCodes()
                        {
                            code = phoneCodes[i]
                        };
                        db.PhoneCodes.Add(codes);
                        db.SaveChanges();
                    }
                }
            }
        }
    }
}
